FROM node:18.17.1-alpine


WORKDIR /frontend

COPY frontend/package.json /frontend/

RUN npm install 
RUN npm install axios@1.5.1
RUN npm install react-router-dom


COPY frontend ./

RUN npm run build

EXPOSE 80

CMD tail -f /dev/null